[package]
name = "filehost"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.1"
rocket_dyn_templates = {version = "0.2.0", features = ["tera"]}
serde = "1.0.210"
tera = "1.20.0"
toml = "0.8.19"
uuid = "1.10.0"

[features]
