[general]
logging_level = 'verbose'
port = [8000]

[upload]
max_filesize = 128 # In megabytes, 0 to disable.    
lifetime = 60      # In minutes, 0 to disable.

[security]
file_handling = { behaviour = 'allowlist', mime_types = [
    'application/zip-compressed',
    'application/x-7z-compressed',
    'application/x-rar-compressed',
    'application/x-tar-compressed',
    'application/gzip',
    'application/x-bzip2',
    'application/pdf',
    'application/rtf',
    'application/msword',
    'application/vnd.oasis.opendocument.text',
    'image/jpeg',
    'image/png',
    'image/avif',
    'image/webp',
    'image/gif',
    'image/heic',
    'audio/webm',
    'audio/mp3',
    'audio/mp4',
    'audio/ogg',
    'audio/aac',
    'audio/flac',
    'audio/wave',
    'video/mp4',
    'video/x-matrovska',
    'video/webm',
    'video/x-msvideo',
    'video/quicktime',
    'text/plain',
    'text/markdown',
    'text/html'
]} # Choose file handling behaviour. You can either have an allowlist or a denylist 
prescan = true # File hash comparison with VirusTotal

[moderation] 
autoban = [true, 3] # Instantly ban any uploader who recieves n amount of reports
autoban_length = 0  # In days, 0 for an indefinite ban.